#!/bin/bash
# src: http://taka.no32.tk/diary/20050826.html
#KEY=`echo $@ | nkf -WwMQ | tr = %`
KEY=`echo $@ | sed 's/ /%20/'`
echo $@ >> ~/.eng-list # 履歴を保存（不要なら削除）．
URI="http://eow.alc.co.jp/$KEY/UTF-8/"
#RS=`echo '▼ 検索結果本体 ▼' | nkf -w -w80`
RS='検索結果本体'
#RE=`echo '▲ 検索結果本体 ▲' | nkf -w -w80`
RE='検索結果本体'
curl  -e 'http://eow.alc.co.jp/' -A 'Mozilla/5.0' -s "$URI" | \
sed -ne "/$RS/,/$RE/p" | w3m -dump -T 'text/html' | less 
